### ISSUE TITLE
Netease api url seems not working

### ISSUE THREAD

**Issue by atmlvs** [houfukude/douban320k#1]
http://music.163.com/api/search/get
it returns {u'message': u'illegal request!', u'code': 403} when query this url.

**Comment by houfukude** [comment]
1. you need **POST** data although this api name is get

``` python
data = {
            's': name.encode('utf-8'),
            'type': 1,
            'offset': 0,
            'sub': 'false',
            'limit': 20
    }
```

this is at [line 86](https://github.com/houfukude/douban320k/blob/master/douban320k.py#L86)
2. ever Netease api needs the cookies for work

``` python
#set cookie
netsase_cookie = urllib2.build_opener()
netsase_cookie.addheaders.append(('Cookie', 'appver=2.0.2'))
netsase_cookie.addheaders.append(('Referer', 'http://music.163.com'))
```

this is at [line 21](https://github.com/houfukude/douban320k/blob/master/douban320k.py#L21)
